Repository CertifaiAI/classifai, pull requests merged in 2020-11, with the labels that each got.

#224 Sh add shortcutkey
  metadata/bounding-box-keyboard.png
  metadata/segmentation-keyboard.png
  shortcut-key-list.md
Labels: documentation

#225 Build script fail due to version upgrade
  classifai-api/pom.xml
  classifai-core/pom.xml
  classifai-test/pom.xml
  classifai-uberjar/pom.xml
  keyShortcut.md
  pom.xml
  startClassifai.bat
  startClassifai.sh
Labels: bug

#226 Sh empty folder
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
Labels: fix
