Repository CertifaiAI/classifai, pull requests merged in 2021-01, with the labels that each got.

#247 V1.1.0 Release
  classifai-api/pom.xml
  classifai-core/pom.xml
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationServiceable.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegVerticle.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/WelcomeLauncher.java
  classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java
  classifai-core/src/main/java/ai/classifai/util/collection/ConversionHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
  classifai-core/src/main/resources/console/Classifai_Welcome_Handler_V1.1.0.jpg
  classifai-core/src/main/resources/console/Classifai_Welcome_Handler_V2.jpg
  classifai-core/src/main/resources/webroot/assets/csv-logo.svg
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-segmentation-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-segmentation-en.json
  classifai-core/src/main/resources/webroot/assets/jpeg-logo.svg
  classifai-core/src/main/resources/webroot/assets/mp3-logo.svg
  classifai-core/src/main/resources/webroot/assets/mp4-logo.svg
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/main-es2015.21faa4622812da0e566b.js
  classifai-core/src/main/resources/webroot/main-es2015.96484f0bfd8b1fa84d0f.js
  classifai-core/src/main/resources/webroot/main-es5.21faa4622812da0e566b.js
  classifai-core/src/main/resources/webroot/main-es5.96484f0bfd8b1fa84d0f.js
  classifai-test/pom.xml
  classifai-uberjar/pom.xml
  metadata/99145059-4c368480-26a6-11eb-8a97-ffbc9bcf0e02 (1).jpg
  metadata/ocr.png
  pom.xml
  readme.md
  startClassifai.bat
  startClassifai.sh
Labels: enhancement

#265 License header update
  classifai-api/pom.xml
  classifai-api/src/main/java/ai/classifai/ClassifaiApp.java
  classifai-api/src/main/java/ai/classifai/config/DbConfig.java
  classifai-api/src/main/java/ai/classifai/config/PortSelector.java
  classifai-api/src/test/java/ai/classifai/AppTest.java
  classifai-core/pom.xml
  classifai-core/src/main/java/ai/classifai/MainVerticle.java
  classifai-core/src/main/java/ai/classifai/data/type/image/ImageFileType.java
  classifai-core/src/main/java/ai/classifai/database/DatabaseConfig.java
  classifai-core/src/main/java/ai/classifai/database/VerticleServiceable.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationServiceable.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegVerticle.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioServiceable.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/LoaderStatus.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFileSelector.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
  classifai-core/src/main/java/ai/classifai/selector/conversion/ConverterFolderSelector.java
  classifai-core/src/main/java/ai/classifai/selector/filesystem/FileSystemStatus.java
  classifai-core/src/main/java/ai/classifai/ui/component/BrowserHandler.java
  classifai-core/src/main/java/ai/classifai/ui/component/LogHandler.java
  classifai-core/src/main/java/ai/classifai/ui/component/LookFeelSetter.java
  classifai-core/src/main/java/ai/classifai/ui/component/OSManager.java
  classifai-core/src/main/java/ai/classifai/ui/component/ProgramOpener.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/LogoHandler.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/RunningStatus.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/WelcomeLauncher.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/conversion/ConversionSelection.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/conversion/ConverterLauncher.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/conversion/Task.java
  classifai-core/src/main/java/ai/classifai/util/ParamConfig.java
  classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java
  classifai-core/src/main/java/ai/classifai/util/collection/ConversionHandler.java
  classifai-core/src/main/java/ai/classifai/util/collection/ListHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/PdfHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/TifHandler.java
  classifai-core/src/main/java/ai/classifai/util/http/HTTPResponseCode.java
  classifai-core/src/main/java/ai/classifai/util/http/HTTPResponseHandler.java
  classifai-core/src/main/java/ai/classifai/util/message/ErrorCodes.java
  classifai-core/src/main/java/ai/classifai/util/message/ReplyHandler.java
  classifai-core/src/main/java/ai/classifai/util/type/AnnotationType.java
  classifai-core/src/main/java/ai/classifai/util/type/FileFormat.java
  classifai-core/src/main/java/ai/classifai/util/type/OS.java
  classifai-test/pom.xml
  classifai-test/src/main/java/ai/classifai/App.java
  classifai-test/src/test/java/ai/codenamewei/AppTest.java
  classifai-uberjar/pom.xml
  classifai-uberjar/src/main/resources/logback.xml
  pom.xml
  startClassifai.bat
Labels: documentation

#268 Sum v1.1notes
  readme.md
Labels: distribution, documentation

#279 Sum v1.1bugfix
  classifai-core/pom.xml
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
  pom.xml
Labels: fix

#284 Check if data points exist every loading of project
  classifai-api/src/main/java/ai/classifai/ClassifaiApp.java
  classifai-core/src/main/java/ai/classifai/MainVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/util/ParamConfig.java
  classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
  classifai-core/src/main/java/ai/classifai/util/http/HTTPResponseHandler.java
Labels: bug, enhancement, test

#287 load project fix
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
Labels: bug

#288 delete uuid bug fix
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/resources/webroot/assets/csv-logo.svg
  classifai-core/src/main/resources/webroot/assets/jpeg-logo.svg
  classifai-core/src/main/resources/webroot/assets/mp3-logo.svg
  classifai-core/src/main/resources/webroot/assets/mp4-logo.svg
Labels: bug

#290 v1.1.1 console graphic modification
  classifai-core/src/main/java/ai/classifai/ui/launcher/WelcomeLauncher.java
  classifai-core/src/main/resources/console/Classifai_Welcome_Handler_V.1.1.1.jpg
  classifai-core/src/main/resources/console/Classifai_Welcome_Handler_V1.1.0.jpg
Labels: enhancement
