Repository CertifaiAI/classifai, pull requests merged in 2021-07, with the labels that each got.

#451 Add rename function to change log
  CHANGELOG.md
Labels: documentation

#453 Copying and pasting dist folder's contents from Classifai_FrontEnd to classifai's webroot
  .github/workflows/auto_pr.yml
  CHANGELOG.md
  classifai-core/src/main/java/ai/classifai/action/parser/PortfolioParser.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/database/versioning/Version.java
  classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
  classifai-core/src/main/java/ai/classifai/util/ParamConfig.java
  classifai-core/src/main/resources/webroot/1-es2015.1a4c49d42291db64cbca.js
  classifai-core/src/main/resources/webroot/1-es2015.54887c536250237cc9b9.js
  classifai-core/src/main/resources/webroot/1-es2015.9bd38b98fb13070aa286.js
  classifai-core/src/main/resources/webroot/1-es5.1a4c49d42291db64cbca.js
  classifai-core/src/main/resources/webroot/1-es5.54887c536250237cc9b9.js
  classifai-core/src/main/resources/webroot/1-es5.9bd38b98fb13070aa286.js
  classifai-core/src/main/resources/webroot/2-es2015.0df6926d5d897b129453.js
  classifai-core/src/main/resources/webroot/2-es2015.2038622e581a416915c4.js
  classifai-core/src/main/resources/webroot/2-es2015.2ce784feb44d2fab33ee.js
  classifai-core/src/main/resources/webroot/2-es2015.f5d6952a3ce0e47c9b30.js
  classifai-core/src/main/resources/webroot/2-es5.0df6926d5d897b129453.js
  classifai-core/src/main/resources/webroot/2-es5.2038622e581a416915c4.js
  classifai-core/src/main/resources/webroot/2-es5.2ce784feb44d2fab33ee.js
  classifai-core/src/main/resources/webroot/2-es5.f5d6952a3ce0e47c9b30.js
  classifai-core/src/main/resources/webroot/7-es2015.bf569adde8b6994102e6.js
  classifai-core/src/main/resources/webroot/7-es2015.eb227bb50af9a504487e.js
  classifai-core/src/main/resources/webroot/7-es2015.f88b4e1b1a1da5519bb9.js
  classifai-core/src/main/resources/webroot/7-es5.bf569adde8b6994102e6.js
  classifai-core/src/main/resources/webroot/7-es5.eb227bb50af9a504487e.js
  classifai-core/src/main/resources/webroot/7-es5.f88b4e1b1a1da5519bb9.js
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-ms.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-ms.json
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/main-es2015.81aa37678a16b20e8ad5.js
  classifai-core/src/main/resources/webroot/main-es2015.82494a37001f1781a756.js
  classifai-core/src/main/resources/webroot/main-es2015.cf7dfc93bb7e942d3142.js
  classifai-core/src/main/resources/webroot/main-es5.81aa37678a16b20e8ad5.js
  classifai-core/src/main/resources/webroot/main-es5.82494a37001f1781a756.js
  classifai-core/src/main/resources/webroot/main-es5.cf7dfc93bb7e942d3142.js
  classifai-core/src/main/resources/webroot/runtime-es2015.3198093ea55bfffb8bc1.js
  classifai-core/src/main/resources/webroot/runtime-es2015.37d80dd256d611ff15f4.js
  classifai-core/src/main/resources/webroot/runtime-es2015.e5a36dc4c9b4d034b18c.js
  classifai-core/src/main/resources/webroot/runtime-es2015.fbcb8ee6dcb3eed450e9.js
  classifai-core/src/main/resources/webroot/runtime-es5.3198093ea55bfffb8bc1.js
  classifai-core/src/main/resources/webroot/runtime-es5.37d80dd256d611ff15f4.js
  classifai-core/src/main/resources/webroot/runtime-es5.e5a36dc4c9b4d034b18c.js
  classifai-core/src/main/resources/webroot/runtime-es5.fbcb8ee6dcb3eed450e9.js
Labels: auto-pr

#457 Copying and pasting dist folder's contents from Classifai_FrontEnd to classifai's webroot
  classifai-core/src/main/resources/webroot/1-es2015.9b8e6dbeed33cf5b0b2a.js
  classifai-core/src/main/resources/webroot/1-es5.9b8e6dbeed33cf5b0b2a.js
  classifai-core/src/main/resources/webroot/2-es2015.6ca755dbac93ce555932.js
  classifai-core/src/main/resources/webroot/2-es5.6ca755dbac93ce555932.js
  classifai-core/src/main/resources/webroot/7-es2015.123fab8664dd542d92cb.js
  classifai-core/src/main/resources/webroot/7-es5.123fab8664dd542d92cb.js
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/main-es2015.57ffbd8f5885275eaf04.js
  classifai-core/src/main/resources/webroot/main-es5.57ffbd8f5885275eaf04.js
  classifai-core/src/main/resources/webroot/runtime-es2015.77bfe2cb769b557a1b12.js
  classifai-core/src/main/resources/webroot/runtime-es5.77bfe2cb769b557a1b12.js
Labels: auto-pr

#460 🐛 Bug fix for #437
  CHANGELOG.md
  classifai-core/src/main/java/ai/classifai/action/LabelListImport.java
Labels: bug

#461 ✨ New feature to delete image
  CHANGELOG.md
  classifai-core/src/main/java/ai/classifai/action/DeleteProjectData.java
  classifai-core/src/main/java/ai/classifai/action/FileMover.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationServiceable.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegVerticle.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
  classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
  classifai-core/src/main/java/ai/classifai/util/ParamConfig.java
  classifai-core/src/main/java/ai/classifai/util/data/FileHandler.java
  classifai-core/src/main/resources/webroot/2-es2015.2b22c3a230e83a843687.js
  classifai-core/src/main/resources/webroot/2-es5.2b22c3a230e83a843687.js
  classifai-core/src/main/resources/webroot/assets/icons/Certifai UI Icon_Folder.svg
  classifai-core/src/main/resources/webroot/assets/icons/archived.svg
  classifai-core/src/main/resources/webroot/assets/icons/audio.svg
  classifai-core/src/main/resources/webroot/assets/icons/download.svg
  classifai-core/src/main/resources/webroot/assets/icons/gridview.svg
  classifai-core/src/main/resources/webroot/assets/icons/image.svg
  classifai-core/src/main/resources/webroot/assets/icons/last_modify.svg
  classifai-core/src/main/resources/webroot/assets/icons/list_view.svg
  classifai-core/src/main/resources/webroot/assets/icons/more.svg
  classifai-core/src/main/resources/webroot/assets/icons/option.svg
  classifai-core/src/main/resources/webroot/assets/icons/project.svg
  classifai-core/src/main/resources/webroot/assets/icons/search.svg
  classifai-core/src/main/resources/webroot/assets/icons/tabular.svg
  classifai-core/src/main/resources/webroot/assets/icons/text.svg
  classifai-core/src/main/resources/webroot/assets/icons/trash.svg
  classifai-core/src/main/resources/webroot/assets/icons/video.svg
  classifai-core/src/main/resources/webroot/main-es2015.cf7dfc93bb7e942d3142.js
  classifai-core/src/main/resources/webroot/main-es5.cf7dfc93bb7e942d3142.js
Labels: enhancement

#456 🎨 Remove redundant Projectloader param
  classifai-core/src/main/java/ai/classifai/action/parser/PortfolioParser.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/database/wasabis3/WasabiVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
Labels: enhancement

#465 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#467 🐛 Fix create empty project
  CHANGELOG.md
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
  classifai-core/src/main/resources/classifai_overview.png
Labels: bug, distribution

#469 🐛 Deven fix missing rename
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegVerticle.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
Labels: fix

#471 Copying and pasting dist folder's contents from Classifai_FrontEnd to classifai's webroot
  classifai-core/src/main/resources/webroot/1-es2015.2cfe8abc723563eb2eb0.js
  classifai-core/src/main/resources/webroot/1-es2015.8a0870f2f23d43faac96.js
  classifai-core/src/main/resources/webroot/1-es5.2cfe8abc723563eb2eb0.js
  classifai-core/src/main/resources/webroot/1-es5.8a0870f2f23d43faac96.js
  classifai-core/src/main/resources/webroot/6-es2015.d745fdc3184874e13d79.js
  classifai-core/src/main/resources/webroot/6-es2015.e57b4f58cc96d8938ff5.js
  classifai-core/src/main/resources/webroot/6-es5.d745fdc3184874e13d79.js
  classifai-core/src/main/resources/webroot/6-es5.e57b4f58cc96d8938ff5.js
  classifai-core/src/main/resources/webroot/7-es2015.0f2604556407c188a398.js
  classifai-core/src/main/resources/webroot/7-es2015.bc96a251c72c7cca8a9b.js
  classifai-core/src/main/resources/webroot/7-es5.0f2604556407c188a398.js
  classifai-core/src/main/resources/webroot/7-es5.bc96a251c72c7cca8a9b.js
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-ms.json
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/main-es2015.1503daaedb87e0bfc087.js
  classifai-core/src/main/resources/webroot/main-es2015.c389fd104cb34117cc3e.js
  classifai-core/src/main/resources/webroot/main-es5.1503daaedb87e0bfc087.js
  classifai-core/src/main/resources/webroot/main-es5.c389fd104cb34117cc3e.js
  classifai-core/src/main/resources/webroot/runtime-es2015.18f360a94f526af13827.js
  classifai-core/src/main/resources/webroot/runtime-es2015.4a3b980c17847bb26bcd.js
  classifai-core/src/main/resources/webroot/runtime-es5.18f360a94f526af13827.js
  classifai-core/src/main/resources/webroot/runtime-es5.4a3b980c17847bb26bcd.js
Labels: auto-pr

#473 📝 Updated readme with Open Source dev details
  readme.md
Labels: documentation

#474 AIFDP Banner for README
  metadata/AIFDP_Banner.png
  readme.md
Labels: documentation

#475 Create config file for issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#476 Adding auto comment for issue
  .github/workflows/auto_comment.yml
Labels: ci/cd
