Repository CertifaiAI/classifai, pull requests merged in 2021-08, with the labels that each got.

#481 Included Frontend's PR title in auto_pr title
  .github/workflows/auto_pr.yml
Labels: ci/cd

#490 🚀 Change alpha1 to alpha2
  classifai-api/pom.xml
  classifai-cloud/pom.xml
  classifai-core/pom.xml
  classifai-test/pom.xml
  classifai-uberjar/pom.xml
  pom.xml
  startClassifai.bat
  startClassifai.sh
Labels: distribution

#494 From classifai_frontend to classifai's webroot - ✨ Add tutorial modal for user guide
  CHANGELOG.md
  classifai-core/src/main/resources/webroot/1-es2015.2cfe8abc723563eb2eb0.js
  classifai-core/src/main/resources/webroot/1-es2015.85e15a8209c72634901a.js
  classifai-core/src/main/resources/webroot/1-es5.2cfe8abc723563eb2eb0.js
  classifai-core/src/main/resources/webroot/1-es5.85e15a8209c72634901a.js
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-ms.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-ms.json
  classifai-core/src/main/resources/webroot/assets/tutorial/create_project/dm_create_project.png
  classifai-core/src/main/resources/webroot/assets/tutorial/create_project/dm_label_file.png
  classifai-core/src/main/resources/webroot/assets/tutorial/create_project/dm_new_project_btn.png
  classifai-core/src/main/resources/webroot/assets/tutorial/create_project/dm_project_created.png
  classifai-core/src/main/resources/webroot/assets/tutorial/create_project/dm_project_folder.png
  classifai-core/src/main/resources/webroot/assets/tutorial/create_project/dm_project_name.png
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_bbox/dm_draw_bbox_adjust.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_bbox/dm_draw_bbox_annotation_tool.png
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_bbox/dm_draw_bbox_delete_selected_bbox.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_bbox/dm_draw_bbox_draw.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_bbox/dm_draw_bbox_remove_all_label.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_bbox/dm_draw_bbox_select_bbox.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_bbox/dm_draw_bbox_select_label.png
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_adjust_polygon.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_annotation_tool.png
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_delete_selected_polygon.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_draw.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_label.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_remove_all_label.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_remove_previous_polygon_point.gif
  classifai-core/src/main/resources/webroot/assets/tutorial/draw_polygon/dm_draw_polygon_select_polygon.gif
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/main-es2015.512f5064932c04f25bba.js
  classifai-core/src/main/resources/webroot/main-es2015.60125e489eda9e64e667.js
  classifai-core/src/main/resources/webroot/main-es5.512f5064932c04f25bba.js
  classifai-core/src/main/resources/webroot/main-es5.60125e489eda9e64e667.js
  classifai-core/src/main/resources/webroot/runtime-es2015.5c7bec1c452e24e5c7ff.js
  classifai-core/src/main/resources/webroot/runtime-es2015.8344c849ffdab9dced33.js
  classifai-core/src/main/resources/webroot/runtime-es5.5c7bec1c452e24e5c7ff.js
  classifai-core/src/main/resources/webroot/runtime-es5.8344c849ffdab9dced33.js
Labels: auto-pr

#499 ♻️ Deven refactor db response
  classifai-core/src/main/java/ai/classifai/data/type/image/WebpImageData.java
  classifai-core/src/main/java/ai/classifai/database/DBUtils.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegVerticle.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/database/wasabis3/WasabiVerticle.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
  classifai-core/src/main/java/ai/classifai/util/data/FileHandler.java
  classifai-core/src/main/java/ai/classifai/util/project/ProjectHandler.java
Labels: enhancement
