Repository CertifaiAI/classifai, pull requests merged in 2021-12, with the labels that each got.

#521 🐛 Fix missing DB
  classifai-core/src/main/java/ai/classifai/database/JDBCPoolHolder.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
  classifai-core/src/main/java/ai/classifai/dto/api/response/ImageSourceResponse.java
  classifai-core/src/main/java/ai/classifai/dto/api/response/LoadingStatusResponse.java
  classifai-core/src/main/java/ai/classifai/dto/api/response/ProjectStatisticResponse.java
  classifai-core/src/main/resources/webroot/assets/icons/Certifai UI Icon_Folder.svg
  classifai-core/src/main/resources/webroot/assets/icons/archived.svg
  classifai-core/src/main/resources/webroot/assets/icons/audio.svg
  classifai-core/src/main/resources/webroot/assets/icons/download.svg
  classifai-core/src/main/resources/webroot/assets/icons/gridview.svg
  classifai-core/src/main/resources/webroot/assets/icons/image.svg
  classifai-core/src/main/resources/webroot/assets/icons/last_modify.svg
  classifai-core/src/main/resources/webroot/assets/icons/list_view.svg
  classifai-core/src/main/resources/webroot/assets/icons/more.svg
  classifai-core/src/main/resources/webroot/assets/icons/option.svg
  classifai-core/src/main/resources/webroot/assets/icons/project.svg
  classifai-core/src/main/resources/webroot/assets/icons/search.svg
  classifai-core/src/main/resources/webroot/assets/icons/tabular.svg
  classifai-core/src/main/resources/webroot/assets/icons/text.svg
  classifai-core/src/main/resources/webroot/assets/icons/trash.svg
  classifai-core/src/main/resources/webroot/assets/icons/video.svg
Labels: fix

#523 🔥 Remove wasabi service
  classifai-cloud/pom.xml
  classifai-cloud/src/main/java/ai/classifai/util/CloudParamConfig.java
  classifai-cloud/src/main/java/ai/classifai/util/InternetConnection.java
  classifai-cloud/src/main/java/ai/classifai/util/PasswordHash.java
  classifai-cloud/src/main/java/ai/classifai/wasabis3/WasabiImageHandler.java
  classifai-cloud/src/main/java/ai/classifai/wasabis3/WasabiProject.java
  classifai-cloud/src/test/java/ai/classifai/PasswordEncryptDecryptTest.java
  classifai-core/pom.xml
  classifai-core/src/main/java/ai/classifai/MainVerticle.java
  classifai-core/src/main/java/ai/classifai/database/DbConfig.java
  classifai-core/src/main/java/ai/classifai/database/JDBCPoolHolder.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationDB.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
  classifai-core/src/main/java/ai/classifai/database/wasabis3/WasabiQuery.java
  classifai-core/src/main/java/ai/classifai/database/wasabis3/WasabiVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/CloudEndpoint.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/router/endpoint/ProjectEndpoint.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
  classifai-core/src/main/java/ai/classifai/util/project/ProjectInfra.java
  pom.xml
Labels: low priority

#519 ✨ Add image backend
  classifai-core/src/main/java/ai/classifai/dto/api/body/AddImageBody.java
  classifai-core/src/main/java/ai/classifai/dto/api/response/ImageAndFolderToProjectResponse.java
  classifai-core/src/main/java/ai/classifai/dto/api/response/SelectionStatusResponse.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/router/endpoint/AddImageEndpoint.java
  classifai-core/src/main/java/ai/classifai/router/endpoint/ProjectEndpoint.java
  classifai-core/src/main/java/ai/classifai/ui/NativeUI.java
  classifai-core/src/main/java/ai/classifai/ui/enums/ImageAndFolderToProjectStatus.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
Labels: enhancement

#526 ♻️ Include properties according annotation type
  classifai-core/src/main/java/ai/classifai/dto/data/AnnotationPointProperties.java
Labels: bug

#530 From classifai_frontend to classifai's webroot - ♻️ Prevent enlarge icons
  classifai-core/src/main/resources/webroot/1-es2015.783c71cb065db40ada95.js
  classifai-core/src/main/resources/webroot/1-es2015.b7bed6c7973cf1282cf0.js
  classifai-core/src/main/resources/webroot/1-es5.783c71cb065db40ada95.js
  classifai-core/src/main/resources/webroot/1-es5.b7bed6c7973cf1282cf0.js
  classifai-core/src/main/resources/webroot/6-es2015.317de1ca1fd2bf73f6d1.js
  classifai-core/src/main/resources/webroot/6-es2015.3bbbc5f7c79482dccc0e.js
  classifai-core/src/main/resources/webroot/6-es5.317de1ca1fd2bf73f6d1.js
  classifai-core/src/main/resources/webroot/6-es5.3bbbc5f7c79482dccc0e.js
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-ms.json
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/runtime-es2015.1a5acd0a17cf612f6f6e.js
  classifai-core/src/main/resources/webroot/runtime-es2015.2cfca0ad853993413dcd.js
  classifai-core/src/main/resources/webroot/runtime-es5.1a5acd0a17cf612f6f6e.js
  classifai-core/src/main/resources/webroot/runtime-es5.2cfca0ad853993413dcd.js
Labels: auto-pr

#532 From classifai_frontend to classifai's webroot - 🐛 Fix last data point color incorrect
  classifai-core/src/main/resources/webroot/6-es2015.3bbbc5f7c79482dccc0e.js
  classifai-core/src/main/resources/webroot/6-es2015.8b6a7d16ae63ff0c4f5a.js
  classifai-core/src/main/resources/webroot/6-es5.3bbbc5f7c79482dccc0e.js
  classifai-core/src/main/resources/webroot/6-es5.8b6a7d16ae63ff0c4f5a.js
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/runtime-es2015.2baa55179ad1066456e4.js
  classifai-core/src/main/resources/webroot/runtime-es2015.2cfca0ad853993413dcd.js
  classifai-core/src/main/resources/webroot/runtime-es5.2baa55179ad1066456e4.js
  classifai-core/src/main/resources/webroot/runtime-es5.2cfca0ad853993413dcd.js
Labels: auto-pr
