Repository CertifaiAI/classifai, pull requests merged in 2021-06, with the labels that each got.

#397 Fix label not saved for first project
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
  classifai-core/src/main/java/ai/classifai/selector/project/ProjectFolderSelector.java
Labels: bug

#412 Copying and pasting dist folder's contents from Classifai_FrontEnd to classifai's webroot
  classifai-core/src/main/resources/webroot/1-es2015.7ae9cbcffcf4311388d3.js
  classifai-core/src/main/resources/webroot/1-es5.7ae9cbcffcf4311388d3.js
  classifai-core/src/main/resources/webroot/2-es2015.18fe972c2a11e6491472.js
  classifai-core/src/main/resources/webroot/2-es2015.fdc52c1751f145d78b18.js
  classifai-core/src/main/resources/webroot/2-es5.18fe972c2a11e6491472.js
  classifai-core/src/main/resources/webroot/2-es5.fdc52c1751f145d78b18.js
  classifai-core/src/main/resources/webroot/7-es2015.136f962344154b4f9934.js
  classifai-core/src/main/resources/webroot/7-es2015.749244e2a5e51e15a601.js
  classifai-core/src/main/resources/webroot/7-es5.136f962344154b4f9934.js
  classifai-core/src/main/resources/webroot/7-es5.749244e2a5e51e15a601.js
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/data-set-page-ms.json
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/main-es2015.6b2b6321827a4cca26d0.js
  classifai-core/src/main/resources/webroot/main-es5.6b2b6321827a4cca26d0.js
  classifai-core/src/main/resources/webroot/polyfills-es2015.369a62f670b8cf057bae.js
  classifai-core/src/main/resources/webroot/polyfills-es5.8976f9887c76351965db.js
  classifai-core/src/main/resources/webroot/runtime-es2015.125553d6bb8c8c67734a.js
  classifai-core/src/main/resources/webroot/runtime-es2015.3011031ef558d9bde423.js
  classifai-core/src/main/resources/webroot/runtime-es5.125553d6bb8c8c67734a.js
  classifai-core/src/main/resources/webroot/runtime-es5.3011031ef558d9bde423.js
Labels: auto-pr

#416 Update automated PR's description
  .github/workflows/auto_pr.yml
Labels: ci/cd

#419 :memo: Added changes to CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#422 :bookmark: Update to alpha1 in pom.xml
  classifai-api/pom.xml
  classifai-cloud/pom.xml
  classifai-core/pom.xml
  classifai-test/pom.xml
  classifai-uberjar/pom.xml
  pom.xml
  startClassifai.bat
  startClassifai.sh
Labels: dependencies

#423 🔧 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#430 🚑 Remove unnecessary metadata
  classifai-core/src/main/java/ai/classifai/router/CloudEndpoint.java
Labels: high priority

#434 📝 Update readme and changelog for new release
  CHANGELOG.md
  readme.md
Labels: documentation

#442 Copying and pasting dist folder's contents from Classifai_FrontEnd to classifai's webroot
  classifai-core/src/main/resources/webroot/2-es2015.f5d6952a3ce0e47c9b30.js
  classifai-core/src/main/resources/webroot/2-es5.f5d6952a3ce0e47c9b30.js
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-ms.json
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/runtime-es2015.37d80dd256d611ff15f4.js
  classifai-core/src/main/resources/webroot/runtime-es5.37d80dd256d611ff15f4.js
Labels: auto-pr

#445 Add Deven as auto pr reviewer
  .github/workflows/auto_pr.yml
Labels: ci/cd

#447 Sum add last modified meta
  classifai-core/src/main/java/ai/classifai/action/parser/PortfolioParser.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/database/versioning/Version.java
  classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
  classifai-core/src/main/java/ai/classifai/util/ParamConfig.java
Labels: enhancement
