Repository CertifaiAI/classifai, pull requests merged in 2021-02, with the labels that each got.

#293 v2 Database Migration hsql -> h2
  classifai-api/src/main/java/ai/classifai/ClassifaiApp.java
  classifai-api/src/main/java/ai/classifai/config/CLIArgument.java
  classifai-api/src/main/java/ai/classifai/config/PortSelector.java
  classifai-core/pom.xml
  classifai-core/src/main/java/ai/classifai/MainVerticle.java
  classifai-core/src/main/java/ai/classifai/data/type/image/ImageFileType.java
  classifai-core/src/main/java/ai/classifai/database/DatabaseConfig.java
  classifai-core/src/main/java/ai/classifai/database/DbConfig.java
  classifai-core/src/main/java/ai/classifai/database/DbOps.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegVerticle.java
  classifai-core/src/main/java/ai/classifai/database/migration/ArchiveHandler.java
  classifai-core/src/main/java/ai/classifai/database/migration/DbMigration.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/CLIProjectInitiator.java
  classifai-core/src/main/java/ai/classifai/loader/NameGenerator.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFileSelector.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
  classifai-core/src/main/java/ai/classifai/selector/conversion/ConverterFolderSelector.java
  classifai-core/src/main/java/ai/classifai/ui/component/BrowserHandler.java
  classifai-core/src/main/java/ai/classifai/ui/component/LogHandler.java
  classifai-core/src/main/java/ai/classifai/ui/component/LookFeelSetter.java
  classifai-core/src/main/java/ai/classifai/ui/component/OSManager.java
  classifai-core/src/main/java/ai/classifai/ui/component/ProgramOpener.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/LogoLauncher.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/RunningStatus.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/WelcomeLauncher.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/conversion/ConverterLauncher.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/conversion/Task.java
  classifai-core/src/main/java/ai/classifai/util/DateTime.java
  classifai-core/src/main/java/ai/classifai/util/ParamConfig.java
  classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java
  classifai-core/src/main/java/ai/classifai/util/collection/ConversionHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/FileHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/PdfHandler.java
  classifai-core/src/main/java/ai/classifai/util/data/TifHandler.java
  classifai-core/src/main/java/ai/classifai/util/http/HTTPResponseCode.java
  classifai-core/src/main/java/ai/classifai/util/type/AnnotationHandler.java
  classifai-core/src/main/java/ai/classifai/util/type/FileFormat.java
  classifai-core/src/main/java/ai/classifai/util/type/database/H2.java
  classifai-core/src/main/java/ai/classifai/util/type/database/Hsql.java
  classifai-core/src/main/java/ai/classifai/util/type/database/RelationalDb.java
  pom.xml
  startClassifai.sh
Labels: enhancement, in review

#299 Sum v2 UUID conversion
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
  classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/migration/DbMigration.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFileSelector.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
  classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java
  classifai-core/src/main/java/ai/classifai/util/collection/ConversionHandler.java
  classifai-core/src/main/java/ai/classifai/util/collection/UUIDGenerator.java
  classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
Labels: enhancement

#304 Loading bug fix for #302
  classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
Labels: bug

#308 V2 db locked
  classifai-core/src/main/java/ai/classifai/MainVerticle.java
  classifai-core/src/main/java/ai/classifai/database/DbOps.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFileSelector.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
  classifai-core/src/main/java/ai/classifai/ui/launcher/WelcomeLauncher.java
Labels: enhancement

#314 Amal v1.2 fix
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-ms.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-segmentation-cn.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-segmentation-en.json
  classifai-core/src/main/resources/webroot/assets/i18n/image-segmentation-ms.json
  classifai-core/src/main/resources/webroot/assets/i18n/landing-page-cn.json
  classifai-core/src/main/resources/webroot/index.html
  classifai-core/src/main/resources/webroot/main-es2015.37f34aeceb4a59aea04e.js
  classifai-core/src/main/resources/webroot/main-es2015.778894dfdfea8142cdd3.js
  classifai-core/src/main/resources/webroot/main-es5.37f34aeceb4a59aea04e.js
  classifai-core/src/main/resources/webroot/main-es5.778894dfdfea8142cdd3.js
Labels: fix
