Repository CertifaiAI/classifai, pull requests merged in 2021-05, with the labels that each got.

#363 Solving out of memory error when exporting project
  classifai-core/src/main/java/ai/classifai/action/ProjectExport.java
Labels: bug, critical

#369 Bug fix for #365
  classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
Labels: bug

#370 Readme update
  readme.md
Labels: documentation

#373 Fix Label list not imported
  classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
  classifai-core/src/main/java/ai/classifai/selector/project/ProjectFolderSelector.java
Labels: bug

#374 Remove obsolete functions
  classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
  classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFileSelector.java
  classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
Labels: enhancement, in review

#378 Add CHANGELOG.md to repository
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation

#385 Adding automatic PR creation workflow
  .github/workflows/auto_pr.yml
Labels: enhancement

#387 Update auto_pr.yml
  .github/workflows/auto_pr.yml
Labels: fix

#390 Update build & sonar workflow
  .github/workflows/build.yml
  .github/workflows/sonar.yml
Labels: enhancement

#391 Update readme.md
  readme.md
Labels: documentation
